# Generated by Django 4.0.5 on 2022-06-22 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('engine', models.CharField(choices=[('New-davinci', 'Instruct New davinci'), ('Old-davinci', 'Instruct Old davinci'), ('Curie', 'Instruct curie')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
