# Generated by Django 4.0.5 on 2022-06-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='prompt',
        ),
    ]
