# Generated by Django 4.0.5 on 2022-06-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_remove_prompt_engine_remove_prompt_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
