# Generated by Django 4.0.5 on 2022-06-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_alter_prompt_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='engine',
            field=models.CharField(blank=True, choices=[('New Instruct Davinci', 'New Instruct Davinci'), ('Old-davinci', 'Old Instruct davinci'), ('Curie', 'Instruct Curie')], max_length=25, null=True),
        ),
    ]
