# Generated by Django 4.0.5 on 2022-06-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_alter_prompt_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='engine',
            field=models.CharField(blank=True, choices=[('New Instruct Davinci', 'New-davinci'), ('Instruct Davinci', 'Old-davinci'), ('Instruct Curie', 'Curie')], max_length=25, null=True),
        ),
    ]
